const translations = {
  sv: {
    /* ── NAV (shared) ── */
    'nav.home':       'Hem',
    'nav.tcg':        'TCG',
    'nav.music':      'Musik',
    'nav.collection': 'Min samling',

    /* ── INDEX ── */
    'index.cta':         'Kom igång',
    'index.tagline':     'Välj din värld',
    'index.sub':         'Två världar, ett varumärke. Utforska Pokémon Trading Cards eller ge dig in i originalmusikens ljudlandskap — båda skapade med passion.',
    'index.tcg-title':   'Pokémon TCG',
    'index.tcg-text':    'Köp, sälj och värdera din Pokémon-kortsamling. Expertguide för samlare och spelare.',
    'index.tcg-cta':     'Utforska kort ✦',
    'index.music-title': 'Musik',
    'index.music-text':  'Originalljud från kosmos. Ett nytt kapitel skrivs — håll utkik efter vad som kommer.',
    'index.music-cta':   'Kommer snart ✦',

    /* ── TCG PAGE ── */
    'tcg.nav-cta':      'Kontakt',
    'tcg.hero-label':   '✦ Pokémon TCG ✦',
    'tcg.hero-title':   'Kort & samlingar',
    'tcg.hero-sub':     'Köp, sälj och upptäck det verkliga värdet på dina Pokémonkort — med ärlig och passionerad service.',
    'tcg.tab-services': 'Tjänster',
    'tcg.tab-val':      'Värdering',
    'tcg.tab-why':      'Varför Astrelia',
    'tcg.tab-contact':  'Kontakt',

    /* Services */
    'tcg.srv-label':    '✦ Vad vi erbjuder ✦',
    'tcg.srv-title':    'TCG-tjänster',
    'tcg.srv-sub':      'Allt du behöver — oavsett om du bygger en samling, säljer en, eller bara är nyfiken på dess värde.',
    'tcg.buy-title':    'Köp kort',
    'tcg.buy-text':     'Bläddra bland ett kurerat urval av Pokémonkort — från vardagsstaples till sällsynta holographics. Rättvisa priser, kvalitet garanterad.',
    'tcg.buy-cta':      'Kontakta oss ✦',
    'tcg.sell-title':   'Sälj kort',
    'tcg.sell-text':    'Vill du sälja din samling eller ett specifikt kort? Få ett snabbt, ärligt erbjudande utan krångel och en smidig affär.',
    'tcg.sell-cta':     'Kontakta oss ✦',
    'tcg.val-srv-title':'Samlingsvärdering',
    'tcg.val-srv-text': 'Osäker på vad din samling är värd? Skicka in den och få en grundlig, transparent värdering baserad på aktuella marknadspriser.',
    'tcg.val-srv-cta':  'Läs mer om värdering ✦',
    'tcg.scan-title':   'Skanna ett kort direkt',
    'tcg.scan-text':    'Ladda upp ett foto så identifierar vår AI ditt kort, bedömer skicket och hämtar aktuella marknadspriser.',
    'tcg.scan-cta':     'Prova scannern ✦',

    /* Värdering tab */
    'tcg.val-label':        '✦ Värdering ✦',
    'tcg.val-title':        'Värdering av Pokémonkort',
    'tcg.val-p1':           'Få hjälp att förstå värdet på dina Pokémonkort eller din samling. Hos Astrelia kan du börja med en kostnadsfri överblick för att se om din samling verkar innehålla kort av värde.',
    'tcg.val-p2':           'Om du vill gå vidare kan du därefter köpa till en mer djupgående och grundlig värdering, där vi tittar närmare på skick, version, språk och aktuellt marknadsvärde.',
    'tcg.val-req-btn':      'Skicka in värderingsförfrågan ✦',
    'tcg.val-trust':        'En första kontakt är alltid avgiftsfri. Du binder dig inte till något köp eller fortsatt uppdrag.',
    'tcg.val-steps-title':  'Så går värderingen till',
    'tcg.val-s1-title':     'Skicka in bilder',
    'tcg.val-s1-p':         'Skicka tydliga bilder på korten eller samlingen. Vid större samlingar räcker det ofta med översiktsbilder till att börja med.',
    'tcg.val-s2-title':     'Första bedömning',
    'tcg.val-s2-p':         'Vi går igenom bilderna och gör en första uppskattning av om samlingen verkar innehålla kort av värde.',
    'tcg.val-s3-title':     'Fördjupad genomgång vid behov',
    'tcg.val-s3-p':         'Om samlingen verkar ha ett högre värde kan vi komma överens om en mer noggrann genomgång. Då kontrolleras bland annat skick, version, språk och marknadsvärde mer detaljerat.',
    'tcg.val-s3-note':      'Den kostnadsfria överblicken avslutas här. Du väljer själv om du vill gå vidare med en detaljerad värdering.',
    'tcg.val-s4-title':     'Värdering av kort eller samling',
    'tcg.val-s4-p':         'Om du väljer en detaljerad värdering skickas korten eller samlingen till Astrelia enligt överenskommelse. Därefter värderas korten utifrån det upplägg vi har kommit överens om.',
    'tcg.val-s5-title':     'Samlat värderingsdokument',
    'tcg.val-s5-p':         'När värderingen är klar får du ett samlat dokument med den information vi har kommit överens om. Dokumentet kan till exempel innehålla skickbedömning, marknadsvärde, kommentarer och översikt över samlingen.',
    'tcg.val-disc-title':   'Viktigt att veta',
    'tcg.val-disc-p1':      'En värdering från Astrelia är en uppskattning baserad på tillgänglig information, skick och aktuella marknadspriser. Det är inte en garanti för att kortet eller samlingen kommer att säljas för exakt det beloppet.',
    'tcg.val-disc-p2':      'Marknaden för Pokémonkort kan förändras över tid, och ett faktiskt försäljningspris kan bli både högre och lägre än den uppskattade värderingen.',
    'tcg.val-price-title':  'Priser',
    'tcg.val-free-title':   'Kostnadsfri överblick',
    'tcg.val-free-r1':      'Överblick av om samlingen verkar ha värde',
    'tcg.val-free-r1v':     'Kostnadsfritt',
    'tcg.val-free-r2':      'Ny överblick efter första tillfället',
    'tcg.val-free-note':    'Den kostnadsfria överblicken är en första bedömning via bilder — till för att avgöra om samlingen verkar innehålla kort som kan vara värda att gå vidare med.',
    'tcg.val-det-title':    'Detaljerad värdering',
    'tcg.val-det-r1':       'Liten värdering (1–25 kort)',
    'tcg.val-det-r2':       'Standard (26–100 kort)',
    'tcg.val-det-r3':       'Utökad (101–250 kort)',
    'tcg.val-det-r4':       'Stor (251–500 kort)',
    'tcg.val-det-r5':       'Större samling (500+ kort)',
    'tcg.val-det-r6':       'Förseglade produkter (per st)',
    'tcg.val-det-note':     'Priserna gäller per samling. En samling kan inte delas upp i flera mindre paket för att kringgå prisnivåerna. För mycket stora eller osorterade samlingar kan pris och upplägg behöva anpassas.',
    'tcg.val-inc-title':    'Vad ingår i en detaljerad värdering?',
    'tcg.val-inc-1':        'Noggrann skickbedömning',
    'tcg.val-inc-2':        'Aktuellt marknadsvärde',
    'tcg.val-inc-3':        'Sortering av kort',
    'tcg.val-inc-4':        'Skydd till värdefulla kort (sleeves eller toploaders)',
    'tcg.val-inc-5':        'Utförligt dokumenterad värdering',
    'tcg.val-inc-6':        'Samlat dokument med tillgång 24/7 under värderingsprocessen',
    'tcg.val-inc-7':        'Försäkring hos Astrelia',
    'tcg.val-inc-8':        'Avtal',
    'tcg.val-seal-title':   'Förseglade produkter',
    'tcg.val-seal-p':       'Förseglade produkter kan ofta värderas online med tydliga bilder.',
    'tcg.val-seal-l1':      'Marknadsvärde',
    'tcg.val-seal-l2':      'Samlat dokument med tillgång 24/7 under värderingsprocessen vid flera produkter',
    'tcg.val-aff-title':    'Vad påverkar värdet?',
    'tcg.val-aff1-h':       'Skick',
    'tcg.val-aff1-p':       'Repor, vita kanter, böjningar och slitage påverkar värdet — ofta en av de viktigaste faktorerna.',
    'tcg.val-aff2-h':       'Utgåva och set',
    'tcg.val-aff2-p':       'Vissa expansioner, äldre kort och särskilda utgåvor är mer eftertraktade än andra.',
    'tcg.val-aff3-h':       'Språk',
    'tcg.val-aff3-p':       'Engelska, japanska och andra språk kan värderas olika beroende på kort, marknad och efterfrågan.',
    'tcg.val-aff4-h':       'Rarity och version',
    'tcg.val-aff4-p':       'Holo, reverse holo, first edition, promo och secret rare kan alla påverka värdet.',
    'tcg.val-aff5-h':       'Efterfrågan',
    'tcg.val-aff5-p':       'Marknadspriser förändras med tid och samlartrender.',
    'tcg.val-aff6-h':       'Gradering',
    'tcg.val-aff6-p':       'Graderade kort kan ha ett annat värde än ograderade beroende på skick och centering.',
    'tcg.val-ins':          'Allt som skickas till Astrelia hanteras varsamt och förvaras enligt våra rutiner. Kunders egendom omfattas av vår företagsförsäkring.',
    'tcg.val-cta-label':    '✦ Kom igång ✦',
    'tcg.val-cta-title':    'Vill du veta vad dina Pokémonkort kan vara värda?',
    'tcg.val-cta-p':        'Skicka in en värderingsförfrågan med bilder och kort information om din samling. Vi börjar med en kostnadsfri överblick och guidar dig vidare därifrån.',

    /* Why Astrelia */
    'tcg.why-label':    '✦ Varför Astrelia ✦',
    'tcg.why-title':    'Betrodd av samlare',
    'tcg.why-1':        'Genuin passion för Pokémon TCG — inte bara ett företag, utan ett hobby som blivit ett kall.',
    'tcg.why-2':        'Transparenta priser baserade på verklig marknadsdata, så du alltid vet vad du får.',
    'tcg.why-3':        'Personlig service — varje samling behandlas med omsorg och respekt, stor som liten.',
    'tcg.why-4':        'Snabb, pålitlig kommunikation oavsett om du köper ett enda kort eller en hel samling.',
    'tcg.why-btn-scan': 'Skanna ett kort ✦',
    'tcg.why-btn-con':  'Kontakta oss',

    /* Contact */
    'tcg.con-label':      '✦ Hör av dig ✦',
    'tcg.con-title':      'Låt oss göra en affär',
    'tcg.con-sub':        'Har du en samling att värdera? Ett kort att köpa eller sälja?<br />Hör av dig och låt oss göra något av det.',
    'tcg.con-email-t':    'E-post',
    'tcg.con-email-p':    'Skicka ett meddelande och förvänta dig svar inom 24 timmar.',
    'tcg.con-ig-t':       'Instagram',
    'tcg.con-ig-p':       'DM:a oss på Instagram för snabba frågor eller kortfoton.',
    'tcg.con-btn-send':   'Skicka ett meddelande ✦',
    'tcg.con-btn-back':   '← Tillbaka till startsidan',

    /* Footer TCG */
    'tcg.ft-brand':   'Två världar, ett varumärke. Pokémon TCG och musik, skapade med kosmisk passion.',
    'tcg.ft-tcg':     'TCG',
    'tcg.ft-buy':     'Köp kort',
    'tcg.ft-sell':    'Sälj kort',
    'tcg.ft-val':     'Samlingsvärdering',
    'tcg.ft-explore': 'Utforska',
    'tcg.ft-home':    'Hem',
    'tcg.ft-music':   'Musik',
    'tcg.ft-scanner': 'Kortscanner',
    'tcg.ft-follow':  'Följ oss',

    /* ── MUSIC PAGE ── */
    'music.nav-cta':     '← Hem',
    'music.hero-label':  '✦ Musik ✦',
    'music.hero-title':  'Astrelia Sounds',
    'music.hero-sub':    'Ett nytt kreativt universum tar form. Något är på gång.',
    'music.soon-title':  'Kommer snart',
    'music.soon-text':   'Originalmusik är på väg. Det här utrymmet kommer att vara hem för releases, projekt och allt som gör Astrelias sound unikt.<br /><br />Håll utkik — stjärnorna ställer in sig.',
    'music.soon-back':   '← Tillbaka till startsidan',
    'music.ft-brand':    'Två världar, ett varumärke. Pokémon TCG och musik, skapade med kosmisk passion.',
    'music.ft-explore':  'Utforska',
    'music.ft-follow':   'Följ oss',

    /* ── SHARED FOOTER ── */
    'ft.copyright': '© 2026 Astrelia. Alla rättigheter förbehålls.',
    'ft.crafted':   'Skapad med ✦ kosmisk kärlek',
    'ft.vat':       'Alla priser är inklusive moms.',

    /* ── COLLECTION PAGE ── */
    'coll.nav-cta':       '← TCG',
    'coll.hero-label':    '✦ Min samling ✦',
    'coll.title':         'Dina kort',
    'coll.scan-btn':      'Skanna ett kort ✦',
    'coll.signout':       'Logga ut',
    'coll.total':         'Totalt antal kort',
    'coll.forsale':       'Till salu',
    'coll.value':         'Samlingsvärde',
    'coll.filter-all':    'Alla kort',
    'coll.filter-sale':   'Till salu',
    'coll.add-btn':       '+ Lägg till kort',
    'coll.empty-title':   'Inga kort ännu',
    'coll.empty-p':       'Lägg till ditt första kort manuellt eller skanna ett med vår AI-scanner för att komma igång.',
    'coll.add-btn2':      '+ Lägg till kort',
    'coll.bar-forsale':   'kort till salu',
    'coll.bar-text':      'Est. värde:',
    'coll.bar-ready':     '· Redo att skicka för ett erbjudande?',
    'coll.bar-btn':       'Få erbjudande ✦',

    /* ── SCAN PAGE ── */
    'scan.nav-cta':      '← TCG',
    'scan.hero-label':   '✦ Kortscanner ✦',
    'scan.title':        'Identifiera & värdera ditt kort',
    'scan.sub':          'Ladda upp ett foto av fram- och baksidan på ditt Pokémonkort.<br />Vår AI identifierar det, bedömer skicket och hämtar aktuella marknadspriser.',
    'scan.front-label':  'Kortets framsida',
    'scan.back-label':   'Kortets baksida',
    'scan.required':     'Obligatorisk',
    'scan.recommended':  'Rekommenderas',
    'scan.identify-btn': '✦ Identifiera kort',
    'scan.loading':      'Läser av korten…',
    'scan.step-1':       '✦ Skickar till AI-vision',
    'scan.step-2':       '✦ Identifierar kort & skick',
    'scan.step-3':       '✦ Hämtar marknadspriser',
    'scan.try-again':    'Försök igen',
    'scan.card-id':      '✦ Kort identifierat',

    /* ── LOGIN PAGE ── */
    'login.tab-signin':    'Logga in',
    'login.tab-signup':    'Skapa konto',
    'login.label-name':    'Ditt namn',
    'login.ph-name':       'Förnamn',
    'login.label-email':   'E-post',
    'login.ph-email':      'du@exempel.se',
    'login.label-password':'Lösenord',
    'login.ph-pw-current': '••••••••',
    'login.ph-pw-new':     'Min. 6 tecken',
    'login.btn-signin':    'Logga in ✦',
    'login.btn-signup':    'Skapa konto ✦',
    'login.footer':        'Genom att logga in godkänner du våra <a href="#">villkor</a> — din data är säker hos oss ✦',

    /* ── VALUATION FORM ── */
    'vf.label':         '✦ Skicka in ✦',
    'vf.title':         'Skicka in värderingsförfrågan',
    'vf.intro':         'Fyll i formuläret nedan och bifoga gärna tydliga bilder på dina kort eller din samling. Vi återkommer med en första kostnadsfri överblick och guidar dig vidare om en detaljerad värdering kan vara aktuell.',
    'vf.s-contact':     'Kontaktuppgifter',
    'vf.name':          'Namn',
    'vf.name-ph':       'Ditt namn',
    'vf.email':         'E-post',
    'vf.email-ph':      'din@epost.se',
    'vf.optional':      '(valfritt)',
    'vf.phone-ph':      '+46 70 000 00 00',
    'vf.s-collection':  'Om samlingen',
    'vf.q-help':        'Vad vill du ha hjälp med?',
    'vf.h-free':        'Kostnadsfri överblick',
    'vf.h-detail':      'Detaljerad värdering',
    'vf.h-sealed':      'Värdering av förseglad produkt',
    'vf.h-unsure':      'Jag är osäker',
    'vf.q-count':       'Ungefär hur många kort gäller det?',
    'vf.q-type':        'Vad består samlingen av?',
    'vf.t-single':      'Enstaka kort',
    'vf.t-binder':      'Pärm',
    'vf.t-bulk':        'Låda/bulk',
    'vf.t-sealed':      'Förseglade produkter',
    'vf.t-mixed':       'Blandat',
    'vf.q-lang':        'Vilket språk är korten på?',
    'vf.l-en':          'Engelska',
    'vf.l-jp':          'Japanska',
    'vf.l-other':       'Annat',
    'vf.l-mixed':       'Blandat',
    'vf.l-unknown':     'Vet ej',
    'vf.s-images':      'Bilder',
    'vf.upload-label':  'Ladda upp bilder',
    'vf.upload-hint':   'Ladda gärna upp översiktsbilder på samlingen samt närbilder på kort du tror kan vara extra värdefulla. Vid större samlingar behöver du inte fotografera varje kort.',
    'vf.msg-ph':        'Berätta kort om samlingen…',
    'vf.s-agree':       'Godkännanden',
    'vf.ag1':           'Jag förstår att den första överblicken är en uppskattning via bilder.',
    'vf.ag2':           'Jag förstår att en värdering inte är en garanti för framtida försäljningspris.',
    'vf.ag3':           'Jag godkänner att Astrelia behandlar mina kontaktuppgifter för att kunna hantera min förfrågan.',
    'vf.submit':        'Skicka förfrågan ✦',
    'vf.ok-title':      'Tack för din förfrågan',
    'vf.ok-p':          'Vi har tagit emot din värderingsförfrågan och återkommer så snart vi har gått igenom informationen. Om vi behöver fler bilder eller mer information kontaktar vi dig via e-post.',
    'vf.ok-warn':       '❗ Skicka inga kort till Astrelia innan du har fått instruktioner och eventuell överenskommelse från oss.',
  },

  en: {
    /* ── NAV (shared) ── */
    'nav.home':       'Home',
    'nav.tcg':        'TCG',
    'nav.music':      'Music',
    'nav.collection': 'My Collection',

    /* ── INDEX ── */
    'index.cta':         'Get Started',
    'index.tagline':     'Choose your universe',
    'index.sub':         'Two worlds, one brand. Explore the cosmic realm of Pokémon Trading Cards or step into the soundscape of original music — both crafted with passion.',
    'index.tcg-title':   'Pokémon TCG',
    'index.tcg-text':    'Buy, sell, and value your Pokémon card collection. Expert guidance for collectors and players alike.',
    'index.tcg-cta':     'Explore Cards ✦',
    'index.music-title': 'Music',
    'index.music-text':  'Original sounds from the cosmos. A new chapter is being written — stay tuned for what\'s coming.',
    'index.music-cta':   'Coming Soon ✦',

    /* ── TCG PAGE ── */
    'tcg.nav-cta':      'Get in Touch',
    'tcg.hero-label':   '✦ Pokémon TCG ✦',
    'tcg.hero-title':   'Cards & Collections',
    'tcg.hero-sub':     'Buy, sell, and discover the true value of your Pokémon cards — with honest, passionate service.',
    'tcg.tab-services': 'Services',
    'tcg.tab-val':      'Valuation',
    'tcg.tab-why':      'Why Astrelia',
    'tcg.tab-contact':  'Contact',

    /* Services */
    'tcg.srv-label':    '✦ What We Offer ✦',
    'tcg.srv-title':    'TCG Services',
    'tcg.srv-sub':      'Everything you need — whether you\'re building a collection, selling one, or just curious about its worth.',
    'tcg.buy-title':    'Buy Cards',
    'tcg.buy-text':     'Browse a curated selection of Pokémon cards — from everyday staples to rare holographics. Fair prices, quality guaranteed.',
    'tcg.buy-cta':      'Get in touch ✦',
    'tcg.sell-title':   'Sell Cards',
    'tcg.sell-text':    'Looking to move your collection or a specific card? Get a quick, honest offer with no hassle and a smooth transaction.',
    'tcg.sell-cta':     'Get in touch ✦',
    'tcg.val-srv-title':'Collection Valuation',
    'tcg.val-srv-text': 'Not sure what your collection is worth? Send it over and get a thorough, transparent valuation based on current market prices.',
    'tcg.val-srv-cta':  'Learn more about valuation ✦',
    'tcg.scan-title':   'Scan a Card Instantly',
    'tcg.scan-text':    'Upload a photo and our AI will identify your card, assess its condition, and pull live market prices.',
    'tcg.scan-cta':     'Try the Scanner ✦',

    /* Valuation tab */
    'tcg.val-label':        '✦ Valuation ✦',
    'tcg.val-title':        'Pokémon Card Valuation',
    'tcg.val-p1':           'Get help understanding the value of your Pokémon cards or collection. At Astrelia you can start with a free overview to see whether your collection appears to contain cards of value.',
    'tcg.val-p2':           'If you\'d like to proceed, you can then add a more in-depth and thorough valuation, where we look more closely at condition, edition, language, and current market value.',
    'tcg.val-req-btn':      'Submit Valuation Request ✦',
    'tcg.val-trust':        'A first contact is always free of charge. You are not committed to any purchase or ongoing engagement.',
    'tcg.val-steps-title':  'How the Valuation Works',
    'tcg.val-s1-title':     'Send Photos',
    'tcg.val-s1-p':         'Send clear photos of the cards or collection. For larger collections, overview photos are often sufficient to start with.',
    'tcg.val-s2-title':     'Initial Assessment',
    'tcg.val-s2-p':         'We review the photos and make a first estimate of whether the collection appears to contain cards of value.',
    'tcg.val-s3-title':     'In-Depth Review if Needed',
    'tcg.val-s3-p':         'If the collection appears to have higher value, we can agree on a more detailed review — checking condition, edition, language, and market value more closely.',
    'tcg.val-s3-note':      'The free overview ends here. You choose whether to proceed with a detailed valuation.',
    'tcg.val-s4-title':     'Card or Collection Valuation',
    'tcg.val-s4-p':         'If you opt for a detailed valuation, the cards or collection are sent to Astrelia as agreed. The cards are then valued based on the arrangement we have agreed upon.',
    'tcg.val-s5-title':     'Compiled Valuation Document',
    'tcg.val-s5-p':         'When the valuation is complete you receive a compiled document with the information we agreed upon — which may include condition assessment, market value, comments, and a collection overview.',
    'tcg.val-disc-title':   'Important to Know',
    'tcg.val-disc-p1':      'A valuation from Astrelia is an estimate based on available information, condition, and current market prices. It is not a guarantee that the card or collection will sell for exactly that amount.',
    'tcg.val-disc-p2':      'The market for Pokémon cards can change over time, and an actual sale price may be both higher and lower than the estimated valuation.',
    'tcg.val-price-title':  'Pricing',
    'tcg.val-free-title':   'Free Overview',
    'tcg.val-free-r1':      'Overview of whether the collection appears to have value',
    'tcg.val-free-r1v':     'Free',
    'tcg.val-free-r2':      'New overview after the first time',
    'tcg.val-free-note':    'The free overview is a first assessment via photos — intended to determine whether the collection appears to contain cards worth proceeding with.',
    'tcg.val-det-title':    'Detailed Valuation',
    'tcg.val-det-r1':       'Small valuation (1–25 cards)',
    'tcg.val-det-r2':       'Standard (26–100 cards)',
    'tcg.val-det-r3':       'Extended (101–250 cards)',
    'tcg.val-det-r4':       'Large (251–500 cards)',
    'tcg.val-det-r5':       'Larger collection (500+ cards)',
    'tcg.val-det-r6':       'Sealed products (per item)',
    'tcg.val-det-note':     'Prices are per collection. A collection cannot be split into smaller packages to avoid price tiers. For very large or unsorted collections, price and terms may need to be agreed before work begins.',
    'tcg.val-inc-title':    'What\'s Included in a Detailed Valuation?',
    'tcg.val-inc-1':        'Thorough condition assessment',
    'tcg.val-inc-2':        'Current market value',
    'tcg.val-inc-3':        'Card sorting',
    'tcg.val-inc-4':        'Protection for valuable cards (sleeves or toploaders)',
    'tcg.val-inc-5':        'Comprehensively documented valuation',
    'tcg.val-inc-6':        'Compiled document with 24/7 access during the valuation process',
    'tcg.val-inc-7':        'Insurance with Astrelia',
    'tcg.val-inc-8':        'Agreement',
    'tcg.val-seal-title':   'Sealed Products',
    'tcg.val-seal-p':       'Sealed products can often be valued online with clear photos.',
    'tcg.val-seal-l1':      'Market value',
    'tcg.val-seal-l2':      'Compiled document with 24/7 access during the valuation process for multiple products',
    'tcg.val-aff-title':    'What Affects the Value?',
    'tcg.val-aff1-h':       'Condition',
    'tcg.val-aff1-p':       'Scratches, white edges, bends, and wear affect the value — often one of the most important factors.',
    'tcg.val-aff2-h':       'Edition & Set',
    'tcg.val-aff2-p':       'Certain expansions, older cards, and special editions are more sought after than others.',
    'tcg.val-aff3-h':       'Language',
    'tcg.val-aff3-p':       'English, Japanese, and other languages can be valued differently depending on the card, market, and demand.',
    'tcg.val-aff4-h':       'Rarity & Version',
    'tcg.val-aff4-p':       'Holo, reverse holo, first edition, promo, and secret rare can all affect the value.',
    'tcg.val-aff5-h':       'Demand',
    'tcg.val-aff5-p':       'Market prices change with time and collector trends.',
    'tcg.val-aff6-h':       'Grading',
    'tcg.val-aff6-p':       'Graded cards can have a different value than ungraded cards depending on condition and centering.',
    'tcg.val-ins':          'Everything sent to Astrelia is handled with care and stored according to our procedures. Customers\' property is covered by our business insurance.',
    'tcg.val-cta-label':    '✦ Get Started ✦',
    'tcg.val-cta-title':    'Want to know what your Pokémon cards could be worth?',
    'tcg.val-cta-p':        'Submit a valuation request with photos and brief information about your collection. We start with a free overview and guide you from there.',

    /* Why Astrelia */
    'tcg.why-label':    '✦ Why Astrelia ✦',
    'tcg.why-title':    'Trusted by Collectors',
    'tcg.why-1':        'Genuine passion for Pokémon TCG — not just a business, but a hobby turned calling.',
    'tcg.why-2':        'Transparent pricing based on real market data, so you always know what you\'re getting.',
    'tcg.why-3':        'Personal service — every collection is treated with care and respect, big or small.',
    'tcg.why-4':        'Fast, reliable communication whether you\'re buying a single card or an entire collection.',
    'tcg.why-btn-scan': 'Scan a Card ✦',
    'tcg.why-btn-con':  'Get in Touch',

    /* Contact */
    'tcg.con-label':      '✦ Reach Out ✦',
    'tcg.con-title':      'Let\'s Make a Deal',
    'tcg.con-sub':        'Got a collection to value? A card to buy or sell?<br />Reach out and let\'s make something happen.',
    'tcg.con-email-t':    'Email',
    'tcg.con-email-p':    'Send a message and expect a reply within 24 hours.',
    'tcg.con-ig-t':       'Instagram',
    'tcg.con-ig-p':       'DM us on Instagram for quick questions or card photos.',
    'tcg.con-btn-send':   'Send a Message ✦',
    'tcg.con-btn-back':   '← Back to Home',

    /* Footer TCG */
    'tcg.ft-brand':   'Two worlds, one brand. Pokémon TCG and music, crafted with cosmic passion.',
    'tcg.ft-tcg':     'TCG',
    'tcg.ft-buy':     'Buy Cards',
    'tcg.ft-sell':    'Sell Cards',
    'tcg.ft-val':     'Collection Valuation',
    'tcg.ft-explore': 'Explore',
    'tcg.ft-home':    'Home',
    'tcg.ft-music':   'Music',
    'tcg.ft-scanner': 'Card Scanner',
    'tcg.ft-follow':  'Follow',

    /* ── MUSIC PAGE ── */
    'music.nav-cta':     '← Home',
    'music.hero-label':  '✦ Music ✦',
    'music.hero-title':  'Astrelia Sounds',
    'music.hero-sub':    'A new creative universe is taking shape. Something is coming.',
    'music.soon-title':  'Coming Soon',
    'music.soon-text':   'Original music is on the way. This space will be home to releases, projects, and everything that makes Astrelia\'s sound unique.<br /><br />Stay tuned — the stars are aligning.',
    'music.soon-back':   '← Back to Home',
    'music.ft-brand':    'Two worlds, one brand. Pokémon TCG and music, crafted with cosmic passion.',
    'music.ft-explore':  'Explore',
    'music.ft-follow':   'Follow',

    /* ── SHARED FOOTER ── */
    'ft.copyright': '© 2026 Astrelia. All rights reserved.',
    'ft.crafted':   'Crafted with ✦ cosmic love',
    'ft.vat':       'All prices include VAT.',

    /* ── COLLECTION PAGE ── */
    'coll.nav-cta':       '← TCG',
    'coll.hero-label':    '✦ My Collection ✦',
    'coll.title':         'Your Cards',
    'coll.scan-btn':      'Scan a Card ✦',
    'coll.signout':       'Sign Out',
    'coll.total':         'Total Cards',
    'coll.forsale':       'For Sale',
    'coll.value':         'Collection Value',
    'coll.filter-all':    'All Cards',
    'coll.filter-sale':   'For Sale',
    'coll.add-btn':       '+ Add Card',
    'coll.empty-title':   'No cards yet',
    'coll.empty-p':       'Add your first card manually or scan one with our AI scanner to get started.',
    'coll.add-btn2':      '+ Add Card',
    'coll.bar-forsale':   'cards for sale',
    'coll.bar-text':      'Est. value:',
    'coll.bar-ready':     '· Ready to send for an offer?',
    'coll.bar-btn':       'Get Offer ✦',

    /* ── SCAN PAGE ── */
    'scan.nav-cta':      '← TCG',
    'scan.hero-label':   '✦ Card Scanner ✦',
    'scan.title':        'Identify & Value Your Card',
    'scan.sub':          'Upload a photo of the front and back of your Pokémon card.<br />Our AI will identify it, assess its condition, and pull current market prices.',
    'scan.front-label':  'Front of card',
    'scan.back-label':   'Back of card',
    'scan.required':     'Required',
    'scan.recommended':  'Recommended',
    'scan.identify-btn': '✦ Identify Card',
    'scan.loading':      'Reading the cards…',
    'scan.step-1':       '✦ Sending to AI vision',
    'scan.step-2':       '✦ Identifying card & condition',
    'scan.step-3':       '✦ Fetching market prices',
    'scan.try-again':    'Try Again',
    'scan.card-id':      '✦ Card Identified',

    /* ── LOGIN PAGE ── */
    'login.tab-signin':    'Sign In',
    'login.tab-signup':    'Create Account',
    'login.label-name':    'Your Name',
    'login.ph-name':       'First name',
    'login.label-email':   'Email',
    'login.ph-email':      'you@example.com',
    'login.label-password':'Password',
    'login.ph-pw-current': '••••••••',
    'login.ph-pw-new':     'Min. 6 characters',
    'login.btn-signin':    'Sign In ✦',
    'login.btn-signup':    'Create Account ✦',
    'login.footer':        'By signing in you agree to our <a href="#">terms</a> — your data is safe with us ✦',

    /* ── VALUATION FORM ── */
    'vf.label':         '✦ Submit ✦',
    'vf.title':         'Submit a Valuation Request',
    'vf.intro':         'Fill in the form below and feel free to attach clear photos of your cards or collection. We\'ll get back to you with a first free overview and guide you further if a detailed valuation seems relevant.',
    'vf.s-contact':     'Contact Details',
    'vf.name':          'Name',
    'vf.name-ph':       'Your name',
    'vf.email':         'Email',
    'vf.email-ph':      'your@email.com',
    'vf.optional':      '(optional)',
    'vf.phone-ph':      '+1 000 000 0000',
    'vf.s-collection':  'About the Collection',
    'vf.q-help':        'What would you like help with?',
    'vf.h-free':        'Free overview',
    'vf.h-detail':      'Detailed valuation',
    'vf.h-sealed':      'Sealed product valuation',
    'vf.h-unsure':      'I\'m not sure',
    'vf.q-count':       'Approximately how many cards?',
    'vf.q-type':        'What does the collection consist of?',
    'vf.t-single':      'Individual cards',
    'vf.t-binder':      'Binder',
    'vf.t-bulk':        'Box/bulk',
    'vf.t-sealed':      'Sealed products',
    'vf.t-mixed':       'Mixed',
    'vf.q-lang':        'What language are the cards in?',
    'vf.l-en':          'English',
    'vf.l-jp':          'Japanese',
    'vf.l-other':       'Other',
    'vf.l-mixed':       'Mixed',
    'vf.l-unknown':     'Not sure',
    'vf.s-images':      'Images',
    'vf.upload-label':  'Upload images',
    'vf.upload-hint':   'Feel free to upload overview photos of the collection as well as close-ups of cards you think may be particularly valuable. For larger collections you don\'t need to photograph every card.',
    'vf.msg-ph':        'Tell us briefly about the collection…',
    'vf.s-agree':       'Agreements',
    'vf.ag1':           'I understand that the first overview is an estimate based on photos.',
    'vf.ag2':           'I understand that a valuation is not a guarantee of a future sale price.',
    'vf.ag3':           'I agree that Astrelia may process my contact details to handle my request.',
    'vf.submit':        'Submit Request ✦',
    'vf.ok-title':      'Thank You for Your Request',
    'vf.ok-p':          'We have received your valuation request and will get back to you as soon as we have reviewed the information. If we need more photos or information we will contact you by email.',
    'vf.ok-warn':       '❗ Do not send any cards to Astrelia until you have received instructions and a possible agreement from us.',
  }
};

function applyLang(lang) {
  localStorage.setItem('astrelia-lang', lang);
  document.documentElement.lang = lang;
  const t = translations[lang];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (t[key] !== undefined) el.innerHTML = t[key];
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.dataset.i18nPh;
    if (t[key] !== undefined) el.placeholder = t[key];
  });
  document.querySelectorAll('.lang-toggle').forEach(btn => {
    btn.textContent = lang === 'sv' ? 'EN' : 'SV';
  });
}

function toggleLang() {
  const current = localStorage.getItem('astrelia-lang') || 'sv';
  applyLang(current === 'sv' ? 'en' : 'sv');
}

// Apply on load
applyLang(localStorage.getItem('astrelia-lang') || 'sv');
